name: Run For

on:
  schedule:
    - cron: '0 9 * * *'

jobs:
  study:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run index.js 54 times
        run: |
          for i in {1..142}; do
            node index.js
          done
        env:
          DUOLINGO_JWT: ${{ secrets.DUOLINGO_JWT }}
